#!/bin/bash -e

if [ ! -e /etc/udev/rules.d/idlab.rules ]; then
	echo 'SUBSYSTEM=="usb", ENV{DEVTYPE}=="usb_device", SYSFS{idVendor}=="04b4", SYSFS{idProduct}=="1004", MODE="0666"' > /etc/udev/rules.d/idlab.rules
	udevadm control --reload-rules
else
	echo "file already exists"
fi

